name: Build jekyll container

on:
  push:
    tags:
      - 'jekyll-v*'
  pull_request:
    paths:
      - 'jekyll/**'

permissions:
  contents: read
  packages: write

jobs:
  build-jekyll-container:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      component: "jekyll"
      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/jekyll-v') }}
    secrets: inherit
