name: Build graalvm container

on:
  push:
    tags:
      - 'graalvm-v*'
  pull_request:
    paths:
      - 'graalvm/**'
      - '.github/workflows/**'
permissions:
  contents: read
  packages: write

jobs:
  build-graalvm-container:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      component: "graalvm"
      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/graalvm-v') }}
    secrets: inherit
