on:
  push:
    tags:
      - 'plantuml/graalvm-v*'
  pull_request:
    paths:
      - 'plantuml/graalvm/**'
      - '.github/workflows/**'
permissions:
  contents: read
  packages: write

name: plantuml/graalvm

jobs:
  build-plantuml/graalvm-docker-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-docker-image.yml
    with:
      component: "plantuml/graalvm"
      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/plantuml/graalvm-v') }}
    secrets: inherit
