name: Build plantuml-cli container image

on:
  workflow_dispatch:

#  push:
#    tags:
#      - 'plantuml-cli-v*'
#  pull_request:
#    paths:
#      - 'plantuml-cli/**'

permissions:
  contents: read
  packages: write

env:
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  TEST_TAG: plantuml-cli:test
  #WARNING do not use environment variable name BUILD_CONTEXT as it it is used by docker action
  CONTAINER_CONTEXT: plantuml-cli

jobs:
  plantuml-cli-build:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Configure job
        id: conf
        uses: actions/github-script@v6
        with:
          script: |
            // checkout-ref for PR ? for snapshot ? for release ? for manual triggering ?
            console.log(context)
            /*
            TODO define how to compute checkout-ref
            for release ?
            for snapshot ?
            for ci ?
            for manual trigger ?
            for pr ?

            $ {{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/plantuml-cli-v') }}
            */
            const conf = {
              publish: false,
              "checkout-ref": context.ref
            }
            return conf;
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.conf.outputs.checkout-ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PASSWORD }}
      - nme: debugging
        run: |-
          echo conf: ${{ fromJSON(steps.conf.outputs.result) }}
      - name: Build locally
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTAINER_CONTEXT }}
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test container image
        run: |
          docker run --rm --entrypoint /bin/bash ${{ env.TEST_TAG }} container-test.sh
      - name: Push container image
        if:  ${{ steps.conf.outputs.result.publish == true }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTAINER_CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


#    uses: ./.github/workflows/build-container.yml
#    with:
#      component: "plantuml-cli"
#      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/plantuml-cli-v') }}
#    secrets: inherit
#