name: Build plantuml-cli container image

on:
  workflow_dispatch:
    inputs:
      container:
        required: true
        type: choice
        description: container name to build
        options:
          - "plantuml-cli"
          - "graalvm"
          - "jekyll"
      publish:
        required: true
        default: false
        type: boolean
        description: publish the container
#  push:
#    tags:
#      - 'plantuml-cli-v*'
#  pull_request:
#    paths:
#      - 'plantuml-cli/**'

permissions:
  contents: read
  packages: write

env:
  CONTAINER_NAME: ${{ github.event.inputs.container }}
  RELEASE_TAG_PREFIX: ${{ github.event.inputs.container }}-v
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  TEST_TAG: ${{ github.event.inputs.container }}:test

jobs:
  plantuml-cli-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ github.event.inputs.container }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PASSWORD }}
      - name: Build locally
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.event.inputs.container }}
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test container image
        run: |
          docker run --rm --entrypoint /bin/bash ${{ env.TEST_TAG }} container-test.sh
      - name: Push container image
        if:  ${{ github.event.inputs.publish }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.event.inputs.container }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Summary
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
          PUBLISHED: ${{ github.event.inputs.publish }}
          CONTAINER: ${{ github.event.inputs.container }}
        run: |
          echo "## Summary:" >> $GITHUB_STEP_SUMMARY
          echo "Container: $CONTAINER" >> $GITHUB_STEP_SUMMARY
          echo "Published: $PUBLISHED" >> $GITHUB_STEP_SUMMARY

          echo "### Tags" >> $GITHUB_STEP_SUMMARY
          echo "$TAGS" >> $GITHUB_STEP_SUMMARY

          echo "### Labels" >> $GITHUB_STEP_SUMMARY
          echo "$LABELS" >> $GITHUB_STEP_SUMMARY


#    uses: ./.github/workflows/build-container.yml
#    with:
#      component: "plantuml-cli"
#      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/plantuml-cli-v') }}
#    secrets: inherit
#