name: plantuml-cli build container image

on:
  workflow_dispatch:
    inputs:
      publish:
        required: true
        default: false
        type: boolean
        description: publish the container
#  push:
#    tags:
#      - 'plantuml-cli-v*'
#  pull_request:
#    paths:
#      - 'plantuml-cli/**'

permissions:
  contents: read
  packages: write

jobs:
  plantuml-cli-configure-publication:
    uses: ./.github/workflows/publication-flag-strategy.yml
    with:
      releaseTagPrefix: plantuml-cli-v
    secrets: inherit
  plantuml-cli-build-container-image:
    needs: plantuml-cli-configure-publication
    uses: ./.github/workflows/build-container-image.yml
    with:
      container: plantuml-cli
      publish: ${{ contains(needs.plantuml-cli-configure-publication.outputs.publish,true) }}
    secrets: inherit

