name: plantuml-cli build container image

on:
  workflow_dispatch:
    inputs:
      publish:
        required: true
        default: false
        type: boolean
        description: publish the container
      plantuml_version:
        required: false
        type: string
        description: use SNAPSHOT for snapshot release
      plantuml_tag:
        required: false
        type: string
        description: use snapshot for snapshot release
  push:
    tags:
      - 'plantuml-cli-v*'
  pull_request:
    paths:
      - 'plantuml-cli/**'

permissions:
  contents: read
  packages: write

jobs:
  plantuml-cli-configure-publication:
    uses: ./.github/workflows/publication-flag-strategy.yml
    with:
      releaseTagPrefix: plantuml-cli-v
    secrets: inherit
  plantuml-cli-load-plantuml-configuration:
    uses: ./.github/workflows/load-plantuml-configuration.yml
    with:
      container: plantuml-cli
    secrets: inherit
  plantuml-cli-build-container-image:
    needs: 
      - plantuml-cli-configure-publication
      - plantuml-cli-load-plantuml-configuration
    uses: ./.github/workflows/build-container-image.yml
    with:
      container: plantuml-cli
      publish: ${{ contains(needs.plantuml-cli-configure-publication.outputs.publish,true) }}
      plantuml_version: ${{ needs.plantuml-cli-load-plantuml-configuration.outputs.plantuml_version }}
      plantuml_tag: ${{ needs.plantuml-cli-load-plantuml-configuration.outputs.plantuml_tag }}
    secrets: inherit
