on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

env:
  RELEASE_BOT_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ env.RELEASE_BOT_TOKEN }}
          monorepo-tags: true
          command: manifest
