name: Build ${CONTAINER_NAME} container

on:
  push:
    tags:
      - '${CONTAINER_NAME}-v*'
  pull_request:
    paths:
      - '${CONTAINER_NAME}/**'
      - '.github/workflows/**'
permissions:
  contents: read
  packages: write

jobs:
  build-${CONTAINER_NAME}-container:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      component: "${CONTAINER_NAME}"
      publish: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/${CONTAINER_NAME}-v') }}
    secrets: inherit
